using System.Text;
using System.Text.RegularExpressions;
using Ck3MapGen.Io;

namespace Ck3MapGen.Emit;

/// <summary>
/// Writes <c>gen_strip_buildings_effect</c>: a province-scope effect that removes every ordinary
/// building the game knows about, so a county being ruined or abandoned has free slots for the
/// obstacles and the ruin that are about to go on it.
///
/// <para>Why it is generated rather than shipped in the Wilderness set: CK3 has no "remove all
/// buildings" effect, only <c>remove_building = key</c>, and <c>set_holding_type</c> keeps whatever
/// was standing. A developed county arrives at <c>abandon_county_effect</c> with every slot full,
/// <c>add_building</c> then fails with "No building slots available" for each obstacle and for the
/// ruin itself, and the county lands in the ruins realm with no ruin on it — the one state the
/// Ruins set says it must never ship. The only way to clear the slots is to name every key, and
/// the list of keys is the game's, not ours: it changes with every patch, so it is read from the
/// installed game at emit time and never hand-maintained.</para>
///
/// <para>What is left alone, deliberately: <c>type = special</c> and <c>type = great_building</c>
/// (wonders and great projects sit in their own slot and are the one thing a ruin should still
/// have standing), the holding's own level chain (<c>castle_01</c>…, <c>settlement_01</c>,
/// <c>wilderness_01</c> — the primary building is the holding, not a slot), and the Wilderness
/// set's own obstacle and ruin family, which is exactly what the caller is about to place.</para>
/// </summary>
public static partial class BuildingStripWriter
{
    public const string EffectName = "gen_strip_buildings_effect";

    /// <summary>
    /// Emits the effect for the buildings in <paramref name="gameDir"/> plus the Wilderness set's
    /// own. Called whenever the Wilderness set ships, because <c>abandon_county_effect</c> calls
    /// the effect by name and a dangling scripted-effect reference is an error on every load.
    /// </summary>
    public static int Write(string modDir, string gameDir)
    {
        var sources = new List<string> { Path.Combine(gameDir, "common", "buildings") };
        string ours = Path.Combine(StaticFileWriter.BaseDirectory, StaticFileWriter.Wilderness, "common", "buildings");
        if (Directory.Exists(ours)) sources.Add(ours);

        var primaryStems = PrimaryStems(Path.Combine(gameDir, "common", "holdings"));
        var wildernessFamily = WildernessFamily();

        var keys = new SortedSet<string>(StringComparer.Ordinal);
        foreach (string source in sources)
        {
            if (!Directory.Exists(source)) continue;
            foreach (string path in Directory.GetFiles(source, "*.txt"))
                foreach (var (key, type) in Buildings(File.ReadAllText(path)))
                {
                    if (type is "special" or "great_building") continue;
                    if (wildernessFamily.Contains(key) || key.EndsWith("_cleared", StringComparison.Ordinal)) continue;
                    if (primaryStems.Any(stem => LevelOf(stem).IsMatch(key))) continue;
                    keys.Add(key);
                }
        }

        var b = new StringBuilder();
        b.Append("# GENERATED by BuildingStripWriter from the installed game's common/buildings. Do not edit.\n");
        b.Append("#\n");
        b.Append("# Province scope. Removes every ordinary building so the obstacles and the ruin that\n");
        b.Append("# abandon_county_effect and gen_ruin_county_effect place afterwards have a slot to go in.\n");
        b.Append("# Wonders, great projects and the holding's own level building are left standing; the\n");
        b.Append("# wilderness obstacle and ruin family is skipped because it is what the caller is placing.\n");
        b.Append("# Each removal is guarded, so the cost is one has_building test per key on a province\n");
        b.Append("# that is being ruined, and nothing at all anywhere else.\n\n");
        b.Append(EffectName).Append(" = {\n");
        foreach (string key in keys)
            b.Append("\tif = { limit = { has_building = ").Append(key).Append(" } remove_building = ").Append(key).Append(" }\n");
        b.Append("}\n");

        string dir = Path.Combine(modDir, "common", "scripted_effects");
        Directory.CreateDirectory(dir);
        ParadoxText.WriteBom(Path.Combine(dir, "zz_gen_strip_buildings_effects.txt"), b.ToString());
        return keys.Count;
    }

    /// <summary>
    /// Every top-level <c>key = {</c> in a buildings file with its depth-one <c>type</c>, or an
    /// empty type for the ordinary kind. Depth one only: a nested block's <c>type</c> (a modifier's,
    /// a trigger's) must not be read as the building's.
    /// </summary>
    private static IEnumerable<(string Key, string Type)> Buildings(string text)
    {
        string? key = null; string type = "";
        int depth = 0;
        foreach (string raw in text.Split('\n'))
        {
            string line = raw;
            int hash = line.IndexOf('#');
            if (hash >= 0) line = line[..hash];

            if (depth == 0)
            {
                var m = TopKey().Match(line);
                if (m.Success) { key = m.Groups[1].Value; type = ""; }
            }
            else if (depth == 1 && key is not null)
            {
                var m = TypeField().Match(line);
                if (m.Success) type = m.Groups[1].Value;
            }

            foreach (char c in line)
            {
                if (c == '{') depth++;
                else if (c == '}' && --depth == 0 && key is not null)
                {
                    yield return (key, type);
                    key = null;
                }
            }
        }
    }

    /// <summary>
    /// The stem of each holding's <c>primary_building</c> (<c>castle</c> from <c>castle_01</c>),
    /// from the game's holdings and the Wilderness set's. A building named stem + two digits is a
    /// level of that holding, not a slot.
    /// </summary>
    private static List<string> PrimaryStems(string gameHoldings)
    {
        var stems = new List<string>();
        var dirs = new[] { gameHoldings, Path.Combine(StaticFileWriter.BaseDirectory, StaticFileWriter.Wilderness, "common", "holdings") };
        foreach (string dir in dirs)
        {
            if (!Directory.Exists(dir)) continue;
            foreach (string path in Directory.GetFiles(dir, "*.txt"))
                foreach (Match m in PrimaryBuilding().Matches(File.ReadAllText(path)))
                {
                    string stem = Regex.Replace(m.Groups[1].Value, @"_\d+$", "");
                    if (!stems.Contains(stem)) stems.Add(stem);
                }
        }
        return stems;
    }

    /// <summary>
    /// The keys <c>wilderness_holding</c> lists as its buildings — the obstacles and the two ruin
    /// rungs — read from the set's own holdings file so the exclusion follows it.
    /// </summary>
    private static HashSet<string> WildernessFamily()
    {
        var family = new HashSet<string>(StringComparer.Ordinal);
        string path = Path.Combine(StaticFileWriter.BaseDirectory, StaticFileWriter.Wilderness, "common", "holdings", "00_wilderness_holdings.txt");
        if (!File.Exists(path)) return family;

        string text = File.ReadAllText(path);
        int start = text.IndexOf("wilderness_holding = {", StringComparison.Ordinal);
        if (start < 0) return family;
        int list = text.IndexOf("buildings = {", start, StringComparison.Ordinal);
        int end = list < 0 ? -1 : text.IndexOf('}', list);
        if (list < 0 || end < 0) return family;

        foreach (Match m in Regex.Matches(text[(list + "buildings = {".Length)..end], @"[a-z_0-9]+"))
            family.Add(m.Value);
        return family;
    }

    private static Regex LevelOf(string stem) => new($"^{Regex.Escape(stem)}_\\d\\d$");

    [GeneratedRegex(@"^([a-z_0-9]+)\s*=\s*\{")]
    private static partial Regex TopKey();

    [GeneratedRegex(@"^\s*type\s*=\s*([a-z_]+)")]
    private static partial Regex TypeField();

    [GeneratedRegex(@"primary_building\s*=\s*([a-z_0-9]+)")]
    private static partial Regex PrimaryBuilding();
}
