using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using Ck3MapGen.Io;

namespace Ck3MapGen.Emit;

/// <summary>
/// Resizes the holding models — the castles, cities, temples, tribes and walls drawn on every
/// barony — by <see cref="Config.MapConfig.HoldingScale"/>.
///
/// There are two places CK3 will take a size from, and this uses the second:
///
/// * The per-instance <c>scale={ x y z }</c> on every building locator, which
///   <see cref="LocatorWriter"/> already writes as 1. It is the only route that could vary size
///   per province, but vanilla never uses it — all 11,246 of its building instances are 1.0 — so
///   whether the engine composes it into the holding transform at all is unverified.
/// * The entity's own <c>scale</c>, which is a documented part of the entity definition and used
///   by 115 vanilla entities. It is global per model rather than per province, which for a size
///   multiplier is all that is wanted.
///
/// The awkward part is applying it without shipping meshes. An .asset in the mod at the same
/// relative path replaces vanilla's copy of that file, but every <c>pdxmesh</c> in these files
/// names its geometry as a bare filename — <c>file = "building_indian_castle_01.mesh"</c>, no
/// path — and the holdings folder is 110 MB of .mesh we are not going to copy. So the pdxmesh
/// blocks are left entirely alone in vanilla's own files, and this writes one additional .asset
/// that redefines only the <c>entity</c> blocks, each copied verbatim from vanilla with a
/// <c>scale</c> added. Entity scale multiplies the mesh scale rather than replacing it, so the
/// relative sizing the artists authored — vanilla's mesh scales run 0.6 to 1.25 — is preserved.
///
/// Redefining an entity that already exists relies on the later definition winning, which is why
/// the file is named to sort last in its directory on top of already loading after the game's own
/// files. If that assumption is ever wrong the failure is a knob that does nothing, not a map with
/// no holdings on it.
///
/// At <see cref="Config.MapConfig.HoldingScale"/> 1.0 nothing is written at all.
/// </summary>
public static class HoldingModelWriter
{
    /// <summary>
    /// Named to sort after every vanilla file in the same directory. Mod files load after the
    /// game's own, so this is belt and braces rather than the mechanism.
    /// </summary>
    private const string OutputFile = "zzz_generated_holding_scale.asset";

    /// <summary>Below this the models are specks; above it they swallow their neighbours. Both
    /// ends are far outside anything useful and exist only to keep a typo from emptying the map.
    /// </summary>
    private const double MinScale = 0.05, MaxScale = 10.0;

    private static readonly Regex EntityStart =
        new(@"\bentity\s*=\s*\{", RegexOptions.Compiled);

    /// <summary>A <c>scale = 1.25</c> assignment. Only meaningful once its brace depth is checked —
    /// see <see cref="ScaleAssignment"/>.</summary>
    private static readonly Regex ScaleValue =
        new(@"\bscale\s*=\s*(-?\d+(?:\.\d+)?)", RegexOptions.Compiled);

    public static void WriteAll(string modDir, string gameDir, Config.MapConfig cfg)
    {
        string targetDir = Path.Combine(modDir, "gfx", "models", "buildings", "holdings");
        string target = Path.Combine(targetDir, OutputFile);

        double scale = cfg.HoldingScale;

        // Vanilla size writes nothing, and clears anything a previous run at another size left
        // behind — the mod directory is not wiped between runs, and a stale override here would
        // silently outlive the setting that produced it.
        if (Math.Abs(scale - 1.0) < 1e-6)
        {
            if (File.Exists(target)) File.Delete(target);
            Console.WriteLine("  holding models: vanilla size, nothing written");
            return;
        }

        double clamped = Math.Clamp(scale, MinScale, MaxScale);
        if (clamped != scale)
            Console.WriteLine($"  holding models: WARNING HoldingScale {scale:F2} clamped to {clamped:F2}");
        scale = clamped;

        string sourceDir = Path.Combine(gameDir, "gfx", "models", "buildings", "holdings");
        if (!Directory.Exists(sourceDir))
        {
            Console.WriteLine("  holding models: SKIPPED (no vanilla holdings assets to read)");
            return;
        }

        var b = new JominiBuilder();
        b.Comment(string.Create(CultureInfo.InvariantCulture,
            $"""
             Generated by Ck3MapGen. Do not edit; regenerated on every run.
             Holding models at {scale:F2}x vanilla size (MapConfig.HoldingScale).
             Vanilla's own .asset files are untouched: these redefine the entities only,
             so every pdxmesh, texture and LOD still resolves to the game's copy.
             """));
        b.Blank();

        int entities = 0, files = 0;

        // Recursive: the subdirectories are not incidental. cp6, fp3, tgp and tribal hold 77 of the
        // asset files and every tribal, Persian, Chinese, Japanese and SE Asian holding in them.
        foreach (string file in Directory
                     .EnumerateFiles(sourceDir, "*.asset", SearchOption.AllDirectories)
                     .OrderBy(p => p, StringComparer.Ordinal))
        {
            string text = File.ReadAllText(file);
            int before = entities;

            foreach (string block in EntityBlocks(text))
            {
                // Vanilla's entity text with one number rewritten; kept verbatim.
                b.Raw(WithScale(block, scale));
                b.Blank();
                b.Blank();
                entities++;
            }

            if (entities > before) files++;
        }

        if (entities == 0)
        {
            Console.WriteLine("  holding models: SKIPPED (no entity definitions found)");
            return;
        }

        Directory.CreateDirectory(targetDir);
        ParadoxText.WriteNoBom(target, b.ToString());

        Console.WriteLine($"  holding models: {entities} entities from {files} files at {scale:F2}x vanilla size");
    }

    /// <summary>
    /// Every top-level <c>entity={ ... }</c> in one .asset, copied out whole.
    ///
    /// Brace counting rather than a regex because three of these carry nested <c>state</c> and
    /// <c>locator</c> blocks — the ones with smoke particles — and those have to come across
    /// intact. Comments are not skipped: nothing in vanilla's holding assets puts a brace in one.
    /// </summary>
    private static IEnumerable<string> EntityBlocks(string text)
    {
        foreach (Match match in EntityStart.Matches(text))
        {
            int open = text.IndexOf('{', match.Index);
            int end = BlockEnd(text, open);
            if (end > 0) yield return text[match.Index..end];
        }
    }

    /// <summary>The index one past the block whose opening brace is at <paramref name="open"/>.</summary>
    private static int BlockEnd(string text, int open)
    {
        int depth = 0;
        for (int i = open; i < text.Length; i++)
        {
            if (text[i] == '{') depth++;
            else if (text[i] == '}' && --depth == 0) return i + 1;
        }
        return -1;
    }

    /// <summary>
    /// One entity block with the multiplier applied.
    ///
    /// None of vanilla's 324 holding entities carries a scale of its own, so in practice this
    /// always appends. The multiply branch is there because appending a second <c>scale</c> to a
    /// block that already had one would silently discard the artist's value rather than combine
    /// with it, and that is the sort of thing a future DLC introduces without warning.
    /// </summary>
    private static string WithScale(string block, double scale)
    {
        string value;

        if (ScaleAssignment(block) is var (start, length, existing))
        {
            value = Format(existing * scale);
            return block[..start] + value + block[(start + length)..];
        }

        value = Format(scale);
        int close = block.LastIndexOf('}');
        return block[..close] + $"\tscale = {value}\n" + block[close..];
    }

    private static string Format(double value) =>
        value.ToString("0.######", CultureInfo.InvariantCulture);

    /// <summary>
    /// The entity's own <c>scale</c>, or null. Depth matters: a nested <c>state</c> or particle
    /// block can carry a scale that is not the entity's.
    /// </summary>
    private static (int Start, int Length, double Value)? ScaleAssignment(string block)
    {
        foreach (Match match in ScaleValue.Matches(block))
        {
            if (Depth(block, match.Index) != 1) continue;

            var number = match.Groups[1];
            if (double.TryParse(number.Value, NumberStyles.Float, CultureInfo.InvariantCulture,
                    out double value))
                return (number.Index, number.Length, value);
        }

        return null;
    }

    /// <summary>Brace depth at <paramref name="index"/>. Quadratic in principle; these blocks are
    /// three lines long.</summary>
    private static int Depth(string block, int index)
    {
        int depth = 0;
        for (int i = 0; i < index; i++)
        {
            if (block[i] == '{') depth++;
            else if (block[i] == '}') depth--;
        }

        return depth;
    }
}
