# The ck3-tiger.conf file is in standard Paradox script format.
# It should be placed in the top directory of your mod.

languages = {
	# Check English localization
	check = "english"

	skip = "german"
	skip = "french"
	skip = "spanish"
	skip = "russian"
	skip = "simp_chinese"
	skip = "korean"
}

filter = {
    show_vanilla = no
    show_loaded_mods = no

    trigger = {
        severity >= Warning
        confidence >= Reasonable

        # Ignore missing loc in definition and vanilla titular titles
        ignore_keys_in_files = {
            keys = { missing-localization }
            files = {
                "map_data/definition.csv"
                "common/landed_titles/zz_vanilla_titulars.txt"
                "common/landed_titles/00_landed_titles.txt"
            }
        }

        # Ignore warnings in vanilla CB folder
        NAND = {
            severity < Fatal
            file = "common/casus_belli_types/"
        }
    }
}