using Ck3MapGen.Config;
using Ck3MapGen.Emit;
using Ck3MapGen.AppGUI;
using Ck3MapGen.MapGen;
using Ck3MapGen.World;

namespace Ck3MapGen.Core;

public sealed class GenerationOptions
{
    public MapConfig Config { get; set; } = new();
    public string GameDir { get; set; } = GameLocator.FindGameDir() ?? GameLocator.DefaultGameDir;
    public bool WriteHistory { get; set; } = true;
    public bool WritePacked { get; set; } = true;

    /// <summary>
    /// Where the heights come from: a 16-bit PNG on disk, or a Forge pipeline run in memory.
    /// Null means nothing has been chosen yet, and a run cannot start.
    /// </summary>
    public HeightmapProvider? Heightmap { get; set; }

    /// <summary>
    /// The file form of <see cref="Heightmap"/>, kept because the command line and the saved
    /// window state both speak in paths. Setting it installs a file provider; reading it gives
    /// the path back only when a file is what is installed.
    /// </summary>
    public string? HeightmapPath
    {
        get => (Heightmap as FileHeightmapProvider)?.Path;
        set => Heightmap = value is null ? null : new FileHeightmapProvider(value);
    }

    /// <summary>
    /// An Azgaar "Full" JSON export to borrow names, borders and politics from. Optional and always
    /// has been: with no path the generator behaves exactly as it does without one.
    /// </summary>
    public string? AzgaarJsonPath { get; set; }
    public string ModName { get; set; } = DefaultModName;

    public const string DefaultModName = "Procedural Map";
    public static string ModRoot => GameLocator.FindModRoot();
    public static string DefaultModDir => Path.Combine(ModRoot, "proceduralmap");
}

public sealed class GenerationResult
{
    public required MapConfig Config { get; init; }
    public required WorldGrid World { get; init; }
    public required float[] ProvinceElevation { get; init; }
    public required byte[] LandMask { get; init; }
    public required ProvinceMap Provinces { get; init; }
    public required int[] ProvinceOrder { get; init; }
    public required int BaronyCount { get; init; }
    public required int LandCount { get; init; }
    public required int RiverCount { get; init; }
    public required List<MapGen.Title> Titles { get; init; }
    public required byte[] ProvinceLandMask { get; init; }
    public required MapGen.Drainage Drainage { get; init; }
    public required MapGen.TerrainClassifier.Result Terrain { get; init; }
    public required TerrainData Terra { get; init; }

    /// <summary>The imported Azgaar world, or null when none was given.</summary>
    public MapGen.AzgaarImport? Azgaar { get; init; }
    public long ElapsedMs { get; init; }
}

public static class Generator
{
    private static void ApplyWatermark(string modDir, MapConfig cfg)
    {
        string version = "0.8";
        string watermark =
            "# =========================================================\r\n" +
            $"# Generated by Ck3MapGen (v{version})\r\n" +
            "# https://github.com/babylettuce22/ck3procedural\r\n" +
            $"# Seed: {cfg.Seed} | Generated start year: {cfg.StartYear}\r\n" +
            "# =========================================================\r\n\r\n";

        foreach (string file in Directory.EnumerateFiles(modDir, "*.*", SearchOption.AllDirectories))
        {
            string ext = Path.GetExtension(file).ToLowerInvariant();
            if (ext != ".txt" && ext != ".yml" && ext != ".gui") continue;

            // Skip blanked vanilla overrides (which only contain a single newline)
            var info = new FileInfo(file);
            if (info.Length <= 4) continue;

            string content = File.ReadAllText(file, System.Text.Encoding.UTF8);

            // Avoid double-watermarking if a file was already processed
            if (content.Contains("Generated by Ck3MapGen")) continue;

            // Strip existing UTF-8 BOM if present so ParadoxText.WriteBom doesn't duplicate it
            if (content.Length > 0 && content[0] == '\uFEFF')
                content = content[1..];

            Io.ParadoxText.WriteBom(file, watermark + content);
        }
    }
    public static GenerationResult Generate(GenerationOptions options)
    {
        var source = options.Heightmap
            ?? throw new InvalidOperationException("No heightmap given.");

        var cfg = options.Config;
        var image = Stage.Time(source.PhaseName,
            () => source.Produce(cfg, Stage.Cancellation, ConsoleProgress.Instance));
        HeightmapSource.Diagnose(image, cfg);

        var terra = Stage.Time("province elevation",
            () => TerrainData.FromElevation(image.ToElevation(cfg), cfg));

        return FromTerrain(terra, cfg, azgaarJsonPath: options.AzgaarJsonPath);
    }

    public static GenerationResult FromTerrain(
            TerrainData terra,
            MapConfig cfg,
            Action<string, PreviewRenderer.Image>? onPreview = null,
            string? azgaarJsonPath = null)
    {
        var sw = System.Diagnostics.Stopwatch.StartNew();
        var rng = new Rng(cfg.Seed);

        // 1. Initial Relief
        onPreview?.Invoke("Relief", PreviewRenderer.RenderRelief(terra.ProvinceElevation, cfg));

        var world = Stage.Time("coarse world summary", () => WorldBridge.Populate(terra, cfg, rng));
        var provinceElevation = terra.ProvinceElevation;
        var landMask = Stage.Time("land mask", () => Raster.LandMask(terra.Elevation, cfg));

        // 2. The Azgaar export, if there is one.
        //
        // Loaded before anything consumes it rather than beside its first reader, because its
        // readers now sit on both sides of the pipeline: the climate is reanchored on grid.temp
        // and grid.prec, and the province partition is cut inside the export's own borders, so by
        // the time the province grid exists it is already too late. Nothing here depends on that
        // grid — AzgaarRaster keys off cfg.ProvinceWidth/Height, which are config — so reading it
        // first costs nothing.
        //
        // The alignment check moves with it, and gains by the move. It compares the export's land
        // against the heightmap's, and landMask is exactly that, more directly than the
        // post-partition mask it used to read. Reporting it here means a heightmap exported
        // cropped or zoomed is caught before the run is spent on it rather than after.
        var azgaar = MapGen.AzgaarImport.Load(azgaarJsonPath ?? cfg.AzgaarJsonPath, cfg);
        azgaar?.CheckAlignment(landMask);

        // 3. Climate
        var climate = Stage.Time("climate",
            () => MapGen.ClimateModel.Build(cfg, provinceElevation, landMask, new Rng(cfg.Seed ^ 0x0C11), azgaar));
        onPreview?.Invoke("Climate", PreviewRenderer.RenderClimate(climate, cfg));

        // 4. Drainage & Major Rivers
        var drainage = Stage.Time("drainage",
            () => MapGen.Drainage.Build(cfg, provinceElevation, landMask, climate.AnnualMm, rng));
        onPreview?.Invoke("Drainage", PreviewRenderer.RenderDrainage(drainage, provinceElevation, cfg));

        var majorRivers = Stage.Time("major rivers carve",
            () => MajorRivers.ExtractAndCarve(terra.Elevation, cfg.Width, cfg.Height, drainage, cfg, rng));
        terra.MajorRiversList = majorRivers;

        provinceElevation = Stage.Time("recompute province elevation",
            () => Raster.ProvinceElevation(terra.Elevation, cfg));
        terra.ProvinceElevation = provinceElevation;

        landMask = Stage.Time("recompute land mask",
            () => Raster.LandMask(terra.Elevation, cfg));

        // 5. Partition provinces with river seeds
        var provinces = Stage.Time("province partition",
            () => Provinces.Build(landMask, provinceElevation, climate,
                cfg.ProvinceWidth, cfg.ProvinceHeight, cfg, rng, majorRivers, drainage, azgaar));
        Console.WriteLine($"  {provinces.Count} provinces total");

        // --- PREVIEWS READY HERE ---
        onPreview?.Invoke("Provinces", PreviewRenderer.RenderProvinces(provinces, cfg));
        onPreview?.Invoke("Impassable", PreviewRenderer.RenderImpassable(provinces, provinceElevation, cfg));
        onPreview?.Invoke("Rivers", PreviewRenderer.RenderRivers(
            Emit.MapDataWriter.RiverIndices(cfg, provinces, drainage), cfg));

        var provinceLandMask = ProvinceLandMask(cfg, provinces);

        // 6. Terrain
        var terrain = Stage.Time("terrain classification",
            () => MapGen.TerrainClassifier.Classify(cfg, provinceElevation, provinceLandMask,
                climate, new Rng(cfg.Seed ^ 0x7E44), azgaar));
        onPreview?.Invoke("Terrain", PreviewRenderer.RenderTerrain(terrain.Terrain, cfg));

        var order = MapDataWriter.BuildProvinceOrder(provinces, out int baronies, out int landCount, out int riverCount);

        // Before the hierarchy, not after: this decides what shape the hierarchy can be built in,
        // and it is the last point at which re-exporting a larger heightmap is still cheaper than
        // finishing the run.
        Stage.Time("azgaar hierarchy plan", () => azgaar?.PlanHierarchy(provinces, order, baronies));

        // 7. Titles — inside the export's borders when there is one, geometrically when there is not.
        var titles = Stage.Time("title hierarchy",
            () => azgaar?.Plan is not null
                ? MapGen.AzgaarHierarchy.Build(provinces, baronies, order, cfg,
                                               new Rng(cfg.Seed ^ 0x71C1), azgaar)
                : MapGen.Titles.Build(provinces, baronies, order, cfg, new Rng(cfg.Seed ^ 0x71C1)));

        onPreview?.Invoke("Counties", PreviewRenderer.RenderTitles(provinces, order, baronies, landCount, titles, "c"));
        onPreview?.Invoke("Duchies", PreviewRenderer.RenderTitles(provinces, order, baronies, landCount, titles, "d"));
        onPreview?.Invoke("Kingdoms", PreviewRenderer.RenderTitles(provinces, order, baronies, landCount, titles, "k"));
        onPreview?.Invoke("Empires", PreviewRenderer.RenderTitles(provinces, order, baronies, landCount, titles, "e"));

        return new GenerationResult
        {
            Config = cfg,
            World = world,
            ProvinceElevation = provinceElevation,
            LandMask = landMask,
            ProvinceLandMask = provinceLandMask,
            Provinces = provinces,
            ProvinceOrder = order,
            BaronyCount = baronies,
            LandCount = landCount,
            RiverCount = riverCount,
            Titles = titles,
            Drainage = drainage,
            Terrain = terrain,
            Terra = terra,
            Azgaar = azgaar,

            ElapsedMs = sw.ElapsedMilliseconds,
        };
    }
    private static byte[] ProvinceLandMask(MapConfig cfg, ProvinceMap provinces)
    {
        var mask = new byte[cfg.ProvinceWidth * cfg.ProvinceHeight];
        Parallel.For(0, mask.Length, i => mask[i] = provinces.Seeds[provinces.Label[i]].IsLand ? (byte)1 : (byte)0);
        return mask;
    }

    /// <returns>
    /// What a later edit to the mod needs to re-emit part of it without generating again — see
    /// <see cref="Emit.WrittenContent"/>. The command line ignores it.
    /// </returns>
    public static Emit.WrittenContent WriteMod(GenerationResult result, GenerationOptions options,
        string modDir)
    {
        var cfg = result.Config;
        var rng = new Rng(cfg.Seed);

        if (!GameLocator.IsGameDir(options.GameDir))
            throw new DirectoryNotFoundException(
                $"'{options.GameDir}' is not a Crusader Kings III game folder.");

        Console.WriteLine($"Writing mod to {modDir}");
        var sw = System.Diagnostics.Stopwatch.StartNew();

        // Before anything is written, not after: a run that fails halfway should leave a folder
        // holding only this run's output, never this run's mixed with the last one's.
        Emit.ModWriter.ClearModDir(modDir);
        Directory.CreateDirectory(modDir);

        Emit.ModWriter.WriteDescriptors(modDir, options.ModName);

        // The array comes back so the scatter passes can read the surface the game will
        // actually render; see ContentWriter.
        var shippedHeightmap = Stage.Time("map_data (heightmap, provinces, rivers)",
                    () => Emit.MapDataWriter.WriteAll(modDir, cfg, result.Provinces, result.ProvinceOrder,
                        result.BaronyCount, result.LandCount, result.RiverCount, options.WritePacked,
                        result.Terra, result.Drainage));

        var written = Emit.ContentWriter.WriteAll(
                            modDir, options.GameDir, cfg, result.Provinces, result.ProvinceOrder,
                            result.BaronyCount, result.LandCount,
                            result.RiverCount, result.Titles, result.Terra, result.Terrain, rng,
                            shippedHeightmap,
                            options.WriteHistory, result.Drainage, result.Azgaar);

        Stage.Time("watermark", () => ApplyWatermark(modDir, cfg));

        Console.WriteLine($"  done in {sw.ElapsedMilliseconds} ms");
        return written;
    }

    public static void WriteDebugImages(GenerationResult result, string outDir, int scale)
    {
        Directory.CreateDirectory(outDir);
        var rng = new Rng(result.Config.Seed);

        Io.DebugRender.WriteElevation(Path.Combine(outDir, "debug_elevation.png"), result.World, scale);
        Io.DebugRender.WriteTerrain(Path.Combine(outDir, "debug_terrain.png"), result.World, result.Config, scale);
        Io.DebugRender.WriteProvinces(Path.Combine(outDir, "debug_provinces.png"), result.Provinces, rng);

        var classified = result.Terrain;
        Io.DebugRender.WriteTerrainClasses(Path.Combine(outDir, "debug_classes.png"),
            classified.Terrain, result.Config.ProvinceWidth, result.Config.ProvinceHeight);

        Io.DebugRender.WriteKoppen(Path.Combine(outDir, "debug_climate.png"), classified.Climate,
            result.Config.ProvinceWidth, result.Config.ProvinceHeight);

        Io.DebugRender.WriteDrainage(Path.Combine(outDir, "debug_drainage.png"), result.Drainage,
            result.ProvinceElevation, result.Config);

        Io.DebugRender.WriteRivers(Path.Combine(outDir, "debug_rivers.png"),
                    Emit.MapDataWriter.RiverIndices(result.Config, result.Provinces, result.Drainage),
                    result.Config.ProvinceWidth, result.Config.ProvinceHeight);

        Io.DebugRender.WriteField(Path.Combine(outDir, "debug_rainfall.png"),
            classified.Field.AnnualMm, result.ProvinceLandMask,
            result.Config.ProvinceWidth, result.Config.ProvinceHeight);
        Io.DebugRender.WriteField(Path.Combine(outDir, "debug_temperature.png"),
            classified.Field.MeanC, result.ProvinceLandMask,
            result.Config.ProvinceWidth, result.Config.ProvinceHeight);

        // The impassable diagnostic, flat and draped over the relief — the same two views the GUI
        // offers, so the selection can be dialled headlessly against the log's score lines.
        var impassable = PreviewRenderer.RenderImpassable(result);
        Io.PngWriter.WriteRgb8(Path.Combine(outDir, "debug_impassable.png"),
            impassable.Width, impassable.Height, impassable.Rgb);
        {
            var cfg = result.Config;
            var full = Emit.MapDataWriter.ShippedHeightmap(
                cfg, result.Provinces, result.ProvinceOrder, result.LandCount, result.Terra);
            var field = AppGUI.Heightfield.Downsample(full, cfg.Width, cfg.Height, AppGUI.Heightfield.PreviewCols);
            var frame = AppGUI.HeightfieldRenderer.Render(
                field, AppGUI.HeightfieldView.Default, 1600, 900, 1, impassable);
            Io.PngWriter.WriteRgb8(Path.Combine(outDir, "debug_impassable_3d.png"),
                frame.Width, frame.Height, frame.Rgb);
        }

        Console.WriteLine($"Wrote debug images to {outDir}");
    }
}