using System.Text;
using Ck3MapGen.Core;
using Ck3MapGen.Io;
using Ck3MapGen.MapGen;

namespace Ck3MapGen.Emit;

/// <summary>
/// Names for the high elves' Great Works, coined in each high-elf culture's own tongue.
///
/// A Great Work (BaseFilesToCopy/Fantasy, <c>gen_great_work</c>) is sworn once in an elf's life and
/// finished decades later; the user asked that every one be properly named. Script cannot coin a
/// word, so the names are made here: <see cref="NamesPerCulture"/> per high-elf culture, as loc
/// keys <c>gen_gw_word_&lt;culture&gt;_&lt;n&gt;</c>, plus the <c>GenGwWorkWord</c> customizable
/// localization that picks one from the two variables the oath stores on the maker
/// (<c>var:gen_gw_name_culture</c>, <c>var:gen_gw_name_index</c>). A maker whose culture has no list
/// (an heir of another people who took the work up) falls back to <c>gen_gw_word_fallback_&lt;n&gt;</c>
/// in the Fantasy set's own loc. The artifact's name is resolved once, when it is made, so a name
/// never shifts afterwards.
///
/// Written only on worlds with races (the Fantasy set is shipped exactly then), from its own Rng
/// stream, so nothing else in the world moves.
/// </summary>
public static class GreatWorkNameWriter
{
    /// <summary>Kept in step with the script's index roll (gen_gw_begin_effect: 1–12).</summary>
    public const int NamesPerCulture = 12;

    public static int WriteAll(string modDir, IEnumerable<Culture> cultures, EthnicityMap ethnicities, Rng rng)
    {
        var elvish = cultures
            .Where(c => !c.Inherited && ethnicities.For(c).Archetype == RaceArchetype.HighElf)
            .ToList();

        var loc = new LocFile();
        var custom = new StringBuilder();
        custom.Append("# Generated by GreatWorkNameWriter: the high elves' Great Work names, per culture.\n");
        custom.Append("# Read by gen_gw_complete_effect / gen_gw_seal_unfinished_effect (Fantasy set).\n\n");
        custom.Append("GenGwWorkWord = {\n\ttype = character\n\n");

        foreach (var culture in elvish)
        {
            var used = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            for (int i = 1; i <= NamesPerCulture; i++)
            {
                // A work's name should carry some weight: six letters at least ("Itho" reads as a
                // nickname), and never the same as another work of this people.
                string name = culture.Tongue.CompoundName(rng);
                for (int retry = 0; retry < 8 && (name.Length < 6 || used.Contains(name)); retry++)
                    name = culture.Tongue.CompoundName(rng);
                used.Add(name);

                string key = $"gen_gw_word_{culture.Key}_{i}";
                loc.AddBuilt(key, name);
                custom.Append("\ttext = {\n\t\ttrigger = {\n")
                      .Append($"\t\t\tvar:gen_gw_name_culture ?= culture:{culture.Key}\n")
                      .Append($"\t\t\tvar:gen_gw_name_index ?= {i}\n")
                      .Append("\t\t}\n")
                      .Append($"\t\tlocalization_key = {key}\n\t}}\n");
            }
        }

        // No list for this maker's people: the Fantasy set's hand-written elvish names, by index.
        for (int i = 1; i <= NamesPerCulture; i++)
        {
            custom.Append("\ttext = {\n\t\ttrigger = {\n")
                  .Append($"\t\t\tvar:gen_gw_name_index ?= {i}\n")
                  .Append("\t\t}\n")
                  .Append($"\t\tlocalization_key = gen_gw_word_fallback_{i}\n\t}}\n");
        }
        custom.Append("\ttext = {\n\t\tfallback = yes\n\t\tlocalization_key = gen_gw_word_fallback_1\n\t}\n}\n");

        string customDir = Path.Combine(modDir, "common", "customizable_localization");
        Directory.CreateDirectory(customDir);
        ParadoxText.WriteBom(Path.Combine(customDir, "zz_gen_great_work_names.txt"), custom.ToString());

        string locDir = Path.Combine(modDir, "localization", "english");
        Directory.CreateDirectory(locDir);
        loc.Write(Path.Combine(locDir, "gen_great_work_names_l_english.yml"));

        return elvish.Count;
    }
}
