using Ck3MapGen.Config;
using Ck3MapGen.Core;
using Ck3MapGen.World;

namespace Ck3MapGen.MapGen;

public sealed class ProvinceSeed
{
    public int X;
    public int Y;
    public bool IsLand;

    /// <summary>
    /// Land, but declared impassable_mountains in default.map: no barony, no holder, armies route
    /// around it. Vanilla has 1,188 of them against 11,301 baronied provinces, and only 4 of those
    /// carry a barony — so this is a third class of province rather than a flag on a normal one.
    /// </summary>
    public bool IsImpassable;
}

/// <summary>Pixel-level province assignment at provinces-map resolution.</summary>
public sealed class ProvinceMap
{
    public required int Width;
    public required int Height;

    /// <summary>Index into <see cref="Seeds"/> for every pixel. Never -1 after partitioning.</summary>
    public required int[] Label;

    public required List<ProvinceSeed> Seeds;

    public int Count => Seeds.Count;
}

/// <summary>
/// Port of the province partitioner in jsck3mapper/run.js.
///
/// Provinces are grown by a multi-source Dijkstra from seed points, using geodesic distance
/// with an absolute land/sea barrier: a land seed can never claim a sea pixel and vice versa.
/// That barrier is what makes provinces follow coastlines instead of spilling across them, and
/// it is why the partition must run on the mask rather than on raw distance.
/// </summary>
public static class Provinces
{
    /// <summary>8-neighbour offsets with their costs; the last four are diagonals.</summary>
    private static readonly (int Dx, int Dy, float Cost, bool Diagonal)[] Dirs =
    [
        (-1, 0, 1f, false), (1, 0, 1f, false), (0, -1, 1f, false), (0, 1, 1f, false),
        (-1, -1, 1.41421356f, true), (1, -1, 1.41421356f, true),
        (-1, 1, 1.41421356f, true), (1, 1, 1.41421356f, true),
    ];

    public static ProvinceMap Build(byte[] mask, float[] elevation, int width, int height,
        MapConfig cfg, Rng rng)
    {
        var sw = System.Diagnostics.Stopwatch.StartNew();

        var seeds = PlaceSeeds(mask, width, height, cfg, rng);
        Console.WriteLine($"  seeded {seeds.Count(s => s.IsLand)} land / " +
                          $"{seeds.Count(s => !s.IsLand)} sea provinces ({sw.ElapsedMilliseconds} ms)");

        sw.Restart();
        EnsureSeedsCoverComponents(mask, width, height, seeds);

        var label = Partition(mask, elevation, width, height, cfg, seeds);
        Console.WriteLine($"  voronoi partition ({sw.ElapsedMilliseconds} ms)");

        var map = new ProvinceMap { Width = width, Height = height, Label = label, Seeds = seeds };
        RepairUnlabeled(map, mask);
        DissolveTinyProvinces(map, mask, cfg);
        MarkImpassable(map, elevation, mask, cfg);
        return map;
    }

    /// <summary>
    /// Merges away provinces below <see cref="MapConfig.MinProvincePixels"/>.
    ///
    /// This is not in ck2rpg but it is not optional: a province of a handful of pixels has no
    /// interior, so CK3 cannot derive its borders, centroid or locator positions. It then fails
    /// inside geometry code, which logs *nothing* — a crash with an empty log is the signature.
    /// EnsureSeedsCoverComponents guarantees every speck of an island becomes a province, so
    /// without this pass they are generated by the dozen.
    /// </summary>
    private static void DissolveTinyProvinces(ProvinceMap map, byte[] mask, MapConfig cfg)
    {
        int merged = 0, flipped = 0;

        // Merging only ever grows the survivor, so a couple of passes converge.
        for (int pass = 0; pass < 4; pass++)
        {
            var area = new int[map.Count];
            foreach (int label in map.Label) area[label]++;

            var tiny = new List<int>();
            for (int i = 0; i < area.Length; i++)
                if (area[i] > 0 && area[i] < cfg.MinProvincePixels) tiny.Add(i);
            if (tiny.Count == 0) break;

            // Shared border length per (tiny province, neighbour) pair.
            var borders = new Dictionary<int, Dictionary<int, int>>();
            foreach (int t in tiny) borders[t] = [];

            for (int cell = 0; cell < map.Label.Length; cell++)
            {
                int label = map.Label[cell];
                if (!borders.TryGetValue(label, out var counts)) continue;

                int x = cell % map.Width, y = cell / map.Width;
                foreach (var (dx, dy, _, _) in Dirs)
                {
                    int nx = x + dx, ny = y + dy;
                    if (nx < 0 || ny < 0 || nx >= map.Width || ny >= map.Height) continue;
                    int other = map.Label[ny * map.Width + nx];
                    if (other == label) continue;
                    counts[other] = counts.GetValueOrDefault(other) + 1;
                }
            }

            var reassign = new Dictionary<int, int>();
            foreach (int t in tiny)
            {
                var counts = borders[t];
                if (counts.Count == 0) continue; // a whole isolated component; nothing to merge into

                // Prefer a neighbour in the same domain so land never absorbs sea.
                int best = -1, bestBorder = -1;
                foreach (var (other, border) in counts)
                {
                    if (map.Seeds[other].IsLand != map.Seeds[t].IsLand) continue;
                    if (border <= bestBorder) continue;
                    best = other;
                    bestBorder = border;
                }

                if (best >= 0)
                {
                    reassign[t] = best;
                    merged++;
                    continue;
                }

                // A tiny island with no same-domain neighbour: drown it, as ck2rpg's
                // tiny-island handling does, and give the pixels to the surrounding water.
                foreach (var (other, border) in counts)
                {
                    if (border <= bestBorder) continue;
                    best = other;
                    bestBorder = border;
                }
                if (best >= 0)
                {
                    reassign[t] = best;
                    flipped++;
                }
            }

            if (reassign.Count == 0) break;

            for (int cell = 0; cell < map.Label.Length; cell++)
            {
                if (!reassign.TryGetValue(map.Label[cell], out int target)) continue;
                map.Label[cell] = target;
                mask[cell] = map.Seeds[target].IsLand ? (byte)1 : (byte)0;
            }
        }

        CompactLabels(map);

        if (merged + flipped > 0)
            Console.WriteLine($"  dissolved {merged} tiny provinces, drowned {flipped} tiny islands " +
                              $"(min {cfg.MinProvincePixels} px)");
    }

    /// <summary>
    /// Flags the most mountainous land provinces as impassable_mountains.
    ///
    /// Ranked by the share of the province standing above the mountain line rather than by mean
    /// height, so a province is impassable because it is *mostly* mountain, not because it happens
    /// to contain one peak. A floor on that share stops a map with little high ground from having
    /// impassable provinces forced on it just to reach the target count.
    ///
    /// Vanilla's proportion is the reference: 1,188 impassable against 11,301 baronied provinces.
    /// </summary>
    private static void MarkImpassable(ProvinceMap map, float[] elevation, byte[] mask, MapConfig cfg)
    {
        double share = Math.Clamp(cfg.ImpassableShareOfLand, 0, 0.5);
        if (share <= 0) return;

        // The mountain line, as a percentile of this map's own land — the same basis the terrain
        // classifier and the heightmap's hypsometry use, so "mountain" means one thing throughout.
        var land = new List<float>();
        for (int i = 0; i < elevation.Length; i += 7)
            if (mask[i] != 0) land.Add(elevation[i]);
        if (land.Count == 0) return;

        land.Sort();
        float mountainLine = land[(int)Math.Clamp(
            land.Count * (1.0 - cfg.TerraMountainShare), 0, land.Count - 1)];

        var total = new int[map.Count];
        var high = new int[map.Count];
        for (int i = 0; i < map.Label.Length; i++)
        {
            int label = map.Label[i];
            if (!map.Seeds[label].IsLand) continue;
            total[label]++;
            if (elevation[i] >= mountainLine) high[label]++;
        }

        var ranked = new List<(int Label, double Share)>();
        for (int i = 0; i < map.Count; i++)
            if (map.Seeds[i].IsLand && total[i] > 0)
                ranked.Add((i, (double)high[i] / total[i]));

        ranked.Sort((a, b) => b.Share.CompareTo(a.Share));

        int want = (int)Math.Round(ranked.Count * share);
        int marked = 0;
        foreach (var (label, mountainous) in ranked)
        {
            if (marked >= want || mountainous < cfg.ImpassableMinMountainShare) break;
            map.Seeds[label].IsImpassable = true;
            marked++;
        }

        Console.WriteLine($"  impassable: {marked} of {ranked.Count} land provinces " +
                          $"(target {want}, mountain line {mountainLine:F0})");
    }

    /// <summary>Drops provinces that no longer own any pixel and renumbers the rest densely.</summary>
    private static void CompactLabels(ProvinceMap map)
    {
        var used = new bool[map.Count];
        foreach (int label in map.Label) used[label] = true;

        var remap = new int[map.Count];
        var kept = new List<ProvinceSeed>();
        for (int i = 0; i < map.Count; i++)
        {
            if (!used[i]) { remap[i] = -1; continue; }
            remap[i] = kept.Count;
            kept.Add(map.Seeds[i]);
        }

        if (kept.Count == map.Count) return;

        for (int i = 0; i < map.Label.Length; i++)
            map.Label[i] = remap[map.Label[i]];
        map.Seeds = kept;
    }

    /// <summary>
    /// Jittered-grid seeding. Spacing comes from the target province *area*, so the province count
    /// falls out of how much land there is rather than being fixed in advance.
    ///
    /// It used to work the other way round — spacing was solved from a target count — which meant
    /// a map kept the same number of provinces at every resolution, and a barony at <c>tiny</c>
    /// covered 1/81 of the pixels one at <c>vanilla</c> did. See <see cref="MapConfig.CountyScale"/>.
    /// </summary>
    private static List<ProvinceSeed> PlaceSeeds(byte[] mask, int width, int height, MapConfig cfg, Rng rng)
    {
        int landSpacing = Spacing(cfg.BaronyPixels);
        int seaSpacing = Spacing(cfg.SeaZonePixels);

        long landPixels = 0;
        for (int i = 0; i < mask.Length; i++) if (mask[i] == 1) landPixels++;

        Console.WriteLine($"  province grid: land every {landSpacing} px " +
                          $"({cfg.BaronyPixels:F0} px each, ~{landPixels / Math.Max(1, cfg.BaronyPixels):F0} " +
                          $"expected), sea every {seaSpacing} px");

        var seeds = new List<ProvinceSeed>();
        Scatter(landSpacing, isLand: true);
        Scatter(seaSpacing, isLand: false);
        return seeds;

        static int Spacing(double targetArea)
            => Math.Max(2, (int)Math.Round(Math.Sqrt(Math.Max(4.0, targetArea))));

        void Scatter(int spacing, bool isLand)
        {
            byte want = isLand ? (byte)1 : (byte)0;
            for (int gy = 0; gy < height; gy += spacing)
            {
                for (int gx = 0; gx < width; gx += spacing)
                {
                    // Jitter inside the cell, then snap to the nearest pixel of the right
                    // domain so seeds never land on the wrong side of a coastline.
                    int x = Math.Min(width - 1, gx + rng.Int(0, spacing - 1));
                    int y = Math.Min(height - 1, gy + rng.Int(0, spacing - 1));
                    if (mask[y * width + x] != want) continue;
                    seeds.Add(new ProvinceSeed { X = x, Y = y, IsLand = isLand });
                }
            }
        }
    }

    /// <summary>
    /// Port of ensureSeedsCoverComponents(). Any connected land or sea region without a seed
    /// would be left unlabeled by the Dijkstra, so every component gets at least one.
    /// </summary>
    private static void EnsureSeedsCoverComponents(byte[] mask, int width, int height,
        List<ProvinceSeed> seeds)
    {
        var component = new int[mask.Length];
        Array.Fill(component, -1);

        var seeded = new HashSet<int>();
        var queue = new int[mask.Length];
        int components = 0;
        var representative = new List<int>();

        for (int start = 0; start < mask.Length; start++)
        {
            if (component[start] != -1) continue;

            int id = components++;
            representative.Add(start);
            byte domain = mask[start];

            int head = 0, tail = 0;
            queue[tail++] = start;
            component[start] = id;

            while (head < tail)
            {
                int cell = queue[head++];
                int cx = cell % width, cy = cell / width;
                foreach (var (dx, dy, _, _) in Dirs)
                {
                    int nx = cx + dx, ny = cy + dy;
                    if (nx < 0 || ny < 0 || nx >= width || ny >= height) continue;
                    int n = ny * width + nx;
                    if (component[n] != -1 || mask[n] != domain) continue;
                    component[n] = id;
                    queue[tail++] = n;
                }
            }
        }

        foreach (var seed in seeds)
            seeded.Add(component[seed.Y * width + seed.X]);

        int added = 0;
        for (int id = 0; id < components; id++)
        {
            if (seeded.Contains(id)) continue;
            int cell = representative[id];
            seeds.Add(new ProvinceSeed
            {
                X = cell % width,
                Y = cell / width,
                IsLand = mask[cell] == 1,
            });
            added++;
        }

        if (added > 0)
            Console.WriteLine($"  added {added} seeds to cover otherwise-unreachable components");
    }

    /// <summary>
    /// Multi-source Dijkstra. Diagonal moves additionally require both orthogonal cells between
    /// source and target to be in the same domain, which stops provinces leaking through a
    /// one-pixel diagonal gap in a coastline.
    /// </summary>
    private static int[] Partition(byte[] mask, float[] elevation, int width, int height,
        MapConfig cfg, List<ProvinceSeed> seeds)
    {
        int n = width * height;
        var label = new int[n];
        var dist = new float[n];
        Array.Fill(label, -1);
        Array.Fill(dist, float.MaxValue);

        // Reference slope, so the weight means the same thing on any map. Sampled rather than
        // measured exactly: this only has to set the scale.
        float terrainCost = (float)Math.Max(0, cfg.ProvinceTerrainCost);
        double total = 0;
        int samples = 0;
        for (int i = width; i < n - width; i += 97)
        {
            if (mask[i] == 0 || mask[i - 1] == 0) continue;
            total += Math.Abs(elevation[i] - elevation[i - 1]);
            samples++;
        }
        float invRef = samples == 0 || total <= 0 ? 0f : (float)(samples / (total * 3.0));

        var heap = new MinHeap(n);
        for (int i = 0; i < seeds.Count; i++)
        {
            int k = seeds[i].Y * width + seeds[i].X;
            label[k] = i;
            dist[k] = 0;
            heap.Push(k, 0);
        }

        while (heap.TryPop(out int cell, out float d))
        {
            if (d > dist[cell]) continue; // stale entry

            int li = label[cell];
            byte domain = mask[cell];
            int x = cell % width, y = cell / width;

            foreach (var (dx, dy, cost, diagonal) in Dirs)
            {
                int nx = x + dx, ny = y + dy;
                if (nx < 0 || ny < 0 || nx >= width || ny >= height) continue;

                int nk = ny * width + nx;
                if (mask[nk] != domain) continue;

                if (diagonal)
                {
                    if (mask[y * width + nx] != domain) continue;
                    if (mask[ny * width + x] != domain) continue;
                }

                // Terrain-aware cost: stepping across a slope costs more than stepping along a
                // flat, so the frontier stalls at ridgelines and two provinces meet there. With a
                // uniform cost the partition is a plain geodesic voronoi and boundaries fall
                // wherever the seeds happen to be equidistant, cutting straight over mountains.
                float nd = d + cost * (1f + terrainCost * MathF.Abs(elevation[nk] - elevation[cell]) * invRef);
                if (nd >= dist[nk]) continue;
                dist[nk] = nd;
                label[nk] = li;
                heap.Push(nk, nd);
            }
        }

        return label;
    }

    /// <summary>
    /// Port of repairUnlabeled(). Anything the Dijkstra could not reach is handed to the label
    /// of its nearest labeled neighbour, so no pixel is left without a province.
    /// </summary>
    private static void RepairUnlabeled(ProvinceMap map, byte[] mask)
    {
        var label = map.Label;
        var queue = new List<int>();

        for (int i = 0; i < label.Length; i++)
            if (label[i] >= 0) queue.Add(i);

        int unlabeled = label.Length - queue.Count;
        if (unlabeled == 0) return;

        int head = 0;
        while (head < queue.Count)
        {
            int cell = queue[head++];
            int x = cell % map.Width, y = cell / map.Width;
            foreach (var (dx, dy, _, _) in Dirs)
            {
                int nx = x + dx, ny = y + dy;
                if (nx < 0 || ny < 0 || nx >= map.Width || ny >= map.Height) continue;
                int nk = ny * map.Width + nx;
                if (label[nk] >= 0) continue;
                label[nk] = label[cell];
                queue.Add(nk);
            }
        }

        Console.WriteLine($"  repaired {unlabeled} unlabeled pixels");
    }
}

/// <summary>
/// Binary min-heap keyed by float, with lazy invalidation — a cell may be pushed more than
/// once and stale entries are skipped on pop. Equivalent to makeMinHeap in run.js.
/// </summary>
internal sealed class MinHeap(int capacity)
{
    private int[] _keys = new int[Math.Max(16, capacity / 4)];
    private float[] _priorities = new float[Math.Max(16, capacity / 4)];
    private int _count;

    public void Push(int key, float priority)
    {
        if (_count == _keys.Length)
        {
            Array.Resize(ref _keys, _count * 2);
            Array.Resize(ref _priorities, _count * 2);
        }

        int i = _count++;
        _keys[i] = key;
        _priorities[i] = priority;

        while (i > 0)
        {
            int parent = (i - 1) / 2;
            if (_priorities[parent] <= _priorities[i]) break;
            Swap(i, parent);
            i = parent;
        }
    }

    public bool TryPop(out int key, out float priority)
    {
        if (_count == 0)
        {
            key = -1;
            priority = 0;
            return false;
        }

        key = _keys[0];
        priority = _priorities[0];

        _count--;
        if (_count > 0)
        {
            _keys[0] = _keys[_count];
            _priorities[0] = _priorities[_count];

            int i = 0;
            while (true)
            {
                int left = 2 * i + 1, right = left + 1, smallest = i;
                if (left < _count && _priorities[left] < _priorities[smallest]) smallest = left;
                if (right < _count && _priorities[right] < _priorities[smallest]) smallest = right;
                if (smallest == i) break;
                Swap(i, smallest);
                i = smallest;
            }
        }

        return true;
    }

    private void Swap(int a, int b)
    {
        (_keys[a], _keys[b]) = (_keys[b], _keys[a]);
        (_priorities[a], _priorities[b]) = (_priorities[b], _priorities[a]);
    }
}
